openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the Production RAG Backend with FastAPI + OpenAI Agents SDK + Qdrant
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/chat:
    post:
      summary: Send a message to the RAG chatbot
      description: Processes a user query and returns a response based on the humanoid robotics knowledge base
      operationId: chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Chat

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's question or message
          example: "How does ROS2 work with humanoid robotics?"
          minLength: 1
          maxLength: 2000
        conversation_id:
          type: string
          description: Optional conversation ID to maintain context
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        history:
          type: array
          description: Optional conversation history
          items:
            type: object
            required:
              - role
              - content
            properties:
              role:
                type: string
                enum: [user, assistant]
              content:
                type: string
          example:
            - role: "user"
              content: "What is ROS2?"
            - role: "assistant"
              content: "ROS2 is a robotics framework..."
      example:
        message: "How does ROS2 work with humanoid robotics?"
        conversation_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef"

    ChatResponse:
      type: object
      required:
        - response
        - conversation_id
        - timestamp
      properties:
        response:
          type: string
          description: The AI-generated response
          example: "ROS2 provides a middleware framework for humanoid robotics..."
        conversation_id:
          type: string
          description: The conversation ID
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        sources:
          type: array
          description: List of sources used in the response
          items:
            type: string
          example:
            - "https://example.com/humanoid-ros2-integration"
            - "https://example.com/ros2-architecture"
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
          example: "2023-10-20T10:00:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INTERNAL_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "An internal error occurred processing your request"

tags:
  - name: Chat
    description: Chatbot interaction endpoints